config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees
  root 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Constants
  PER_PAGE = 20
end

app/models/employee.rb
class Employee < ApplicationRecord

  # Constants
  GENDER = %w(female male others).freeze

  # Enum
  enum gender: [:female, :male, :others]

  # Association
  belongs_to :user
  # Validations
  validates_presence_of :first_name, :last_name, :age, :gender
  validates_inclusion_of :gender, in: GENDER
  validates_numericality_of :age

  # Methods

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Association
  has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @query = current_user.employees.ransack(params[:q])
    @query.sorts = 'created_at desc' if @query.sorts.empty?
    @pagy, @employees = pagy(@query.result, items: ApplicationRecord::PER_PAGE)
  end

  def show; end

  def new
    @employee = current_user.employees.new
  end

  def create
    @employee = current_user.employees.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee successfully created."}
      else
        flash.now[:errors] = "Invalid record"
        format.html { render 'new'}
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee successfully updated."}
      else
        flash.now[:errors] = "Invalid record"
        format.html { render 'edit'}
      end
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path
  end

  private

  def set_employee
    @employee = current_user.employees.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:age, :designation, :first_name, :gender, :last_name,)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def display_resources_title(resource_name)
    "Your #{resource_name}"
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="row justify-content-md-center">
  <div class="col-6 col-md-4">
    <%= form_for(@employee) do |form| %>

      <div class="form-group">
        <label>First Name</label>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label>Last Name</label>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Age</label>
        <%= form.text_field :age, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Designation</label>
        <%= form.text_field :designation, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Gender</label>
        <%= form.select(:gender, Employee::GENDER.collect { |gender| [gender.humanize, gender] }, {}, {class: 'custom-select mr-sm-2'}) %>
      </div>

      <div class="form-group text-center">
        <%= form.submit "Save", class: 'btn btn-primary' %>
        <%= link_to "Cancel", employees_path, class: "btn btn-warning" %>
      </div>

    <% end %>
  </div>
</div>

app/views/employees/edit.html.erb
<%= render 'form' %>

app/views/employees/index.html.erb
<div class="mx-auto my-8 px-4">
  <div class="flex mb-2">
    <h1><%= display_resources_title('Employees') %></h1>
  </div>
  <% if @employees.present? %>
    <%= search_form_for [@query] do |f| %>
      <div class="form-row align-items-center">
        <div class="col-auto">
          <div class="input-group mb-2">
            <%= f.text_field :first_name_or_last_name_or_designation_cont, class: "form-control", placeholder: "Name" %>
          </div>
        </div>
        <div class="col-auto">
          <div class="input-group mb-2">
            <label class="ml-3 mr-3">From</label>
            <%= f.text_field :created_at_gteq, class: "form-control lg:flex-1", placeholder: "Select from date", autocomplete: 'off', value: params["q"].present? ? params["q"]["created_at_gteq"] : nil %>
          </div>
        </div>
        <div class="col-auto">
          <div class="input-group mb-2">
            <label class="ml-3 mr-3">To</label>
            <%= f.text_field :created_at_lteq, class: "form-control lg:flex-1", placeholder: "Select to date", autocomplete: 'off', value: params["q"].present? ? params["q"]["created_at_lteq"] : nil %>
          </div>
        </div>
        <div class="m-lg-4 text-center">
          <div class="input-group mb-2">
            <%= f.submit "Search", class: "btn btn-primary" %>
          </div>
        </div>

        <div class="col-auto">
          <div class="input-group mb-2">
            <%= link_to 'New Employee', new_employee_path, class: "btn bg-primary-700 btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="bg-white rounded shadow table-responsive">
      <table class="table table-fixed break-words">
        <thead>
        <tr>
          <th class="w-10 py-6 px-4 text-left">S.NO</th>
          <th class="w-10 py-6 px-4 text-left"><%= sort_link(@query, :first_name, [:first_name, :last_name], "Name") %></th>
          <th class="w-10 py-6 px-4 text-left"><%= sort_link(@query, :age) %></th>
          <th class="w-10 py-6 px-4 text-left"><%= sort_link(@query, :gender) %></th>
          <th class="w-10 py-6 px-4 text-left"><%= sort_link(@query, :designation) %></th>
          <th class="w-10 py-6 px-4 text-left"><%= sort_link(@query, :created_at) %></th>
          <th class="w-10 py-6 px-4 text-left"><%= sort_link(@query, :updated_at) %></th>
          <th class="w-10 py-6 px-4 text-left">Actions</th>
        </tr>
        </thead>

        <tbody>
        <% from = @pagy.from %>
        <% @employees.each_with_index do |employee, index| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
            <td class="p-4 py-5 text-left text-gray-700"><%= index + from %></td>
            <td class="p-4 py-5 text-left text-gray-700"><%= employee.name %></td>
            <td class="p-4 py-5 text-left text-gray-700"><%= employee.age %></td>
            <td class="p-4 py-5 text-left text-gray-700"><%= employee.gender %></td>
            <td class="p-4 py-5 text-left text-gray-700"><%= employee.designation %></td>
            <td class="p-4 py-5 text-left text-gray-700"><%= employee.created_at %></td>
            <td class="p-4 py-5 text-left text-gray-700"><%= employee.updated_at %></td>
            <td class="p-4 py-5 uppercase text-left text-gray-700 px-0">
              <%= link_to "View", employee %> |
              <%= link_to "Edit", edit_employee_path(employee) %> |
              <%= link_to 'Delete', employee, method: :delete, data: {remote: true, confirm: "Are you sure?"} %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <% if @pagy.pages > 1 %>
      <div class="text-right">
        <%== pagy_nav(@pagy) %>
      </div>
    <% end %>
  <% else %>
    <div class="bg-white rounded shadow flex flex-col items-center justify-between p-8 lg:flex-row">
      <div class="flex-1 text-center">
        <%= link_to 'New Contact', new_employee_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/employees/new.html.erb
<%= render 'form' %>

app/views/employees/show.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="row justify-content-between">
    <div class="col-4">
      <%= link_to "← Back to Contacts", employees_path, class: "navigation__link" %>
    </div>
    <div class="col-1">
      <%= link_to 'Edit', edit_employee_path(@employee), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="bg-white rounded shadow p-8">
    <div class="flex flex-wrap flex-col md:flex-row">

      <div class="col mt-2">
        <label class="text-black-50">First Name:</label>
        <%= @employee.first_name %>
      </div>

      <div class="col mt-2">
        <label class="text-black-50">Last Name:</label>
        <%= @employee.last_name %>
      </div>

      <div class="col mt-2">
        <label class="text-black-50">Age:</label>
        <%= @employee.age %>
      </div>

      <div class="col mt-2">
        <label class="text-black-50">Designation:</label>
        <%= @employee.designation %>
      </div>

      <div class="col mt-2">
        <label class="text-black-50">Gender:</label>
        <%= @employee.gender %>
      </div>

      <div class="col mt-2">
        <label class="text-black-50">Created At:</label>
        <%= @employee.created_at %>
      </div>

      <div class="col mt-2">
        <label class="text-black-50">Updated At:</label>
        <%= @employee.updated_at %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeCrud</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'shared/flash_message' %>
<%= render 'shared/nav' %>
<div class="mt-5 container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_flash_message.html.erb
<div class="content">
  <div class="text-center">
    <div id="flash">
      <% flash.each do |key, value| %>
        <% if key == "notice" %>
          <div class="alert alert-success alert-dismissible fade show">
            <%= value %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% else %>
            <div class="alert alert-danger alert-dismissible fade show">
              <%= value %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">
  <h5><%= link_to "Employees", employees_path %></h5>
  <div>
    <% if user_signed_in? %>
      <h5><%= link_to "Logout", destroy_user_session_path, method: :delete %></h5>
    <% else %>
      <h5><%= link_to "SignIn", user_session_path %></h5>
      <h5><%= link_to "SignUp", new_user_registration_path %></h5>
    <% end %>
  </div>
</nav>